### ISSUE TITLE
Amend Reggio di Calabria and Reggio nell'Emilia

### ISSUE THREAD

**Issue by nico00** [fabiocaccamo/python-codicefiscale#1]
Very good job, thanks.
You should consider to replace (or at least add) "Reggio di Calabria"  with "Reggio Calabria" and "Reggio nell'Emilia" with "Reggio Emilia" as these are actually the more common names.
Thanks
Nico

**Comment by fabiocaccamo** [comment]
@nico00 thanks for the support. I will add support for alternative names as soon as possible. Feel free to submit a PR if you need it today.
