### ISSUE TITLE
Add validity date to each municipality.

### ISSUE THREAD

**Issue by fabiocaccamo** [fabiocaccamo/python-codicefiscale#12]
This change will resolve the generation of incorrect codes for people born in municipalities that have changed their province over the years.

**Comment by fabiocaccamo** [comment]
[ANPR_archivio_comuni.zip](https://github.com/fabiocaccamo/python-codicefiscale/files/5321592/ANPR_archivio_comuni.zip)

**Comment by SickBoy84** [comment]
link for ANPR download: https://www.anpr.interno.it/portale/tabelle-di-riferimento

**Comment by fabiocaccamo** [comment]
ANPR download link update: 
https://www.anagrafenazionale.interno.it/wp-content/uploads/ANPR_archivio_comuni.csv

**Comment by fabiocaccamo** [comment]
@SickBoy84 in case you are interested there are 2 updates:
- `municipalities.json` data is automatically generated once a week importing data from ANPR.
- `municipalities.json` data [now contains validity dates](https://raw.githubusercontent.com/fabiocaccamo/python-codicefiscale/master/codicefiscale/data/municipalities.json) for each municipality, so it is possible to fix this issue easily.

**Comment by fabiocaccamo** [comment]
Another datasource: 
http://www.istat.it/it/archivio/6789

**Comment by fabiocaccamo** [comment]
Fixed in `0.5.0` version.
