### ISSUE TITLE
Wrong validity check after 0.5.0 version

### ISSUE THREAD

**Issue by m-berto** [fabiocaccamo/python-codicefiscale#123]
**Python version**
3.10

**Package version**
0.8.1

**Current behavior (bug description)**
Some valid fiscal codes validated in versions since 0.5.0 are not validated in later versions.
I cant' provide a real fiscal code to test (for privacy reasons) but i can provide some other details for the debug:

Birth place: MONTECHIARO D’ACQUI
Province: AL
Birth date: 04/03/1940
Sex: M

Birth place: PRIERO
Province: CN
Birth date: 18/01/1941
Sex: F

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-codicefiscale/issues/123">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/123/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/123/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@m-berto thank you for reporting this.

The cause of this issue has been discussed in #113, unfortunately the only thing that can be done is to patch the municipalities data every time someone reports some _"invalid"_ but valid fiscal codes.

**Comment by fabiocaccamo** [comment]
Now I fixed the two municipalities you reported, but I'm sure there are are tens of municipalities having the same problem.
