### ISSUE TITLE
Get all cities/nations names

### ISSUE THREAD

**Issue by TeoLucco** [fabiocaccamo/python-codicefiscale#127]
Crate a method or a property which returns all cities and nations names, in order to have all accepted options for a birth city field

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-codicefiscale/issues/127">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/127/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/127/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@TeoLucco this is a useful feature, I think that having a list of dicts with name and slug would be better, do you agree?

**Comment by TeoLucco** [comment]
I agree, a list of dictionaries with name and slug would be perfect!

**Comment by fabiocaccamo** [comment]
@TeoLucco what do you think about duplicated entries? 
Very often the same municipality is listed multiple times because they changed along the time, (eg. they changed the province they belong to and consequently also their code changed).

I'm starting to think that this is much more complicated than expected.

**Comment by TeoLucco** [comment]
I'd recommend using a HashSet instead of a simple list. For my specific use case, which involves inputting a city name and using it with other fields to call the encode function and check for the matching fiscal code, the code might not be necessary. I plan to use this HashSet to list possible values for the "birthday" field in a Django model, which will be reused in a form with autocomplete functionality.

**Comment by fabiocaccamo** [comment]
@TeoLucco the data comes from here:
https://github.com/fabiocaccamo/python-codicefiscale/blob/main/codicefiscale/data/municipalities.json

**Comment by TeoLucco** [comment]
Do you know which is the meaning of all name fields? there are a lot!

**Comment by fabiocaccamo** [comment]
Indeed, I did it:

`active`: indicates if the municipality is still active or not
`code`: the municipality code
`date_created`: when the municipality has been "created"
`date_deleted`: when the municipality has been "deleted", if empty, it means it's still active
`name`: the official name
`name_alt`: possible alternative name
`name_alt_trans`: possible alternative name translated, sometimes some cities have bilingual name
`name_slugs`: slugs computed from all names for indexing
`name_trans`: the official name translated (often it's empty)
`province`: the province the municipality belongs to

**Comment by fabiocaccamo** [comment]
@TeoLucco you can import methods from the data module to use raw data for your specific needs.
