### ISSUE TITLE
Number of omocodes

### ISSUE THREAD

**Issue by jacopo-j** [fabiocaccamo/python-codicefiscale#13]
According to [Wikipedia](https://it.wikipedia.org/wiki/Codice_fiscale#Omocodie), the total number of "omocodes" that can be derived from a fiscal code is 128, as it includes all possible combinations of number -> letter substitutions (that is 2<sup>7</sup>).

This library only considers (and returns) 8 of them, as it only takes into account one substitution for each digit of the code.

**Comment by canepa** [comment]
You are correct.
Returning only the 8 single substitutions makes the list quite useless.
It should include all the combinations.
It's quite a simple fix, can it be included in the library?

**Comment by fabiocaccamo** [comment]
@canepa and @jacopo-j feel free to submit a PR

**Comment by fabiocaccamo** [comment]
@canepa @jacopo-j have you any update about this issue?

**Comment by jacopo-j** [comment]
I haven't had a chance to work on a PR yet

**Comment by fabiocaccamo** [comment]
@jacopo-j ok, don't worry, thank you for the feedback!

**Comment by canepa** [comment]
@fabiocaccamo I'm not a good enough coder to even touch your great work!

**Comment by fabiocaccamo** [comment]
@jacopo-j @canepa you can upgrade to `0.3.8` version.
