### ISSUE TITLE
Add check commad in the cli

### ISSUE THREAD

**Issue by claudiorivetti** [fabiocaccamo/python-codicefiscale#132]
python -m codicefiscale check CCCFBA85D03L219P

returns true/false

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-codicefiscale/issues/132">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/132/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/132/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@claudiorivetti you can upgrade to `0.9.0`, then `python -m codicefiscale validate {{code}}`
