### ISSUE TITLE
Date Formats

### ISSUE THREAD

**Issue by dp-jason-shaw** [fabiocaccamo/python-codicefiscale#134]
The link in the read me to:
Multiple birthdate formats (date/string) (you can see all the supported string formats [here](https://github.com/fabiocaccamo/python-codicefiscale/blob/main/tests/tests.py#L73))

Does not work... hence, no idea what or how to use the date formats.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-codicefiscale/issues/134">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/134/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/134/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@dp-jason-shaw fixed, thanks for reporting it.
