### ISSUE TITLE
💡 Add this project to awesome-italia-opensource

### ISSUE THREAD

**Issue by FabrizioCafolla** [fabiocaccamo/python-codicefiscale#136]
I founded Italia Open-source, a community that aims to share and grow the Italian open-source world, but more generally to highlight Italian tech excellence.

Our website [italiaopensource.com](https://italiaopensource.com/) is based on open data that reside on the [awesome-italia-opensource](https://github.com/italia-opensource/awesome-italia-opensource) repository, you can add your own open-source project, community tech(s), and much more. All through a simple pull request, you can add your data.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-codicefiscale/issues/136">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/136/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/136/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@FabrizioCafolla thanks for sharing this interesting community, I will add it!

**Comment by FabrizioCafolla** [comment]
@fabiocaccamo of course, you can also include the other open-source projects you maintain.
The only thing is to create a pull request for each project you intend to add.
