### ISSUE TITLE
Birth year

### ISSUE THREAD

**Issue by stef-iula** [fabiocaccamo/python-codicefiscale#15]
**Python version**
3.8.6

**Package version**
0.3.7

**Current behavior (bug description)**
Tax codes with "21" as birth year are decoded as 2021

**Expected behavior**
Tax codes with "21" as birth year decoded correctly as 1921 or 2021

**Comment by fabiocaccamo** [comment]
@stef-iula do you have any idea regarding how to solve this problem?

**Comment by fabiocaccamo** [comment]
Yes, it is really a corner case.
