### ISSUE TITLE
Issue with Incorrect Validation of Valid 'Codice Fiscale'

### ISSUE THREAD

**Issue by dannylessio** [fabiocaccamo/python-codicefiscale#162]
**Python version**
3.11.2

**Package version**
0.9.1

**Current behavior (bug description)**
I've encountered an issue with the library's validation function, where it incorrectly marks a certain Italian "codice fiscale" as invalid. The "codice fiscale" in question is validated correctly on the official website of the Italian "Agenzia delle Entrate."

**Expected behavior**
The library should validate this pattern as it aligns with the format deemed valid by the "Agenzia delle Entrate".

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-codicefiscale/issues/162">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/162/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-codicefiscale/issues/162/pledge.svg">
</picture>
</a>

**Comment by dannylessio** [comment]
Since the matter involves a real "codice fiscale," which is sensitive personal information, I would like to share the specific details privately to avoid any data exposure. Could you please provide a secure method of communication (such as a private email address or a private issue tracker) where I can share the affected "codice fiscale"? This will help in replicating and addressing the validation issue without compromising personal privacy.

Many thanks

**Comment by fabiocaccamo** [comment]
@dannylessio the cause of problem you reported is the same of #113 and #123.

Keeping the `municipalities-patch.json` list updated is complicated, not to mention that other issues of this nature could emerge in the future.

For this reasons I tried to find a permanent solution in #163

**Comment by fabiocaccamo** [comment]
@dannylessio you can upgrade to `0.10.0` version.

**Comment by dannylessio** [comment]
@fabiocaccamo awesome, many thanks!
