### ISSUE TITLE
`codicefiscale.is_valid` with invalid birthplace codes throw TypeException exception

### ISSUE THREAD

**Issue by vermouthmjl** [fabiocaccamo/python-codicefiscale#27]
**Python version**
3.9.13

**Package version**
0.5.0

**Current behavior (bug description)**
When doing the following,
```
x = "FRTMXM74L15D354A"
codicefiscale.is_valid(x)
```
the method throws a `TypeError` with the following stacktrace

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/opt/conda/lib/python3.9/site-packages/codicefiscale/codicefiscale.py", line 477, in is_valid
>     decode(code)
>   File "/opt/conda/lib/python3.9/site-packages/codicefiscale/codicefiscale.py", line 422, in decode
>     for birthplace_option in birthplaces_options:
> TypeError: 'NoneType' object is not iterable

**Expected behavior**
`False`

**Comment by fabiocaccamo** [comment]
Fixed in c336dafde2fb0f2ca2ea58a4020acc240151927c.
