### ISSUE TITLE
Code Z118 (Jugoslavia) not recognised, in general file countries.json don't manage deleted countries

### ISSUE THREAD

**Issue by giobber** [fabiocaccamo/python-codicefiscale#36]
**Python version**
3.10

**Package version**
I'm installing `main` branch with `pip`

**Current behavior (bug description)**
A Fiscal Code with birthplace code set as Z118 (code for ex-country Jugoslavia) are marked as invalid when using `codicefiscale.is_valid()` function. When I open up the countries.json file I cannot find that code inside but I notice that all codes have as `date_created` value "01/01/1900 00:00:00" and `date_deleted` ""
I don't know if this is the desired behaviour, but I think there is no management of deleted foreign country.
In my code I've added an exception for that code (It's only one person in a database) but I want to inform about this behaviour

**Expected behavior**
CF with code Z118  should be recognised as a Foreign Person born in a deleted country

**Comment by fabiocaccamo** [comment]
@giobber countries data is automatically updated every week from this data source:
https://www.anagrafenazionale.interno.it/wp-content/uploads/2021/03/tabella_2_statiesteri.xlsx

If there are some missing countries the only thing that could be done is to post-process the data adding some entries at the end of the update workflow.

I'm sure that there are many other cases like this one, do you have a better data-source that could be used for retrieving more accurate countries info?

**Comment by giobber** [comment]
I've searched for my case on google and i found the history of code for Serbia in this [site](http://www.elesh.it/storiastati/storia_stato.asp?codcat=Z118) 

The site of Agenzia delle Entrate seem to be the right source, but the only page I found instead of data, contains a download for a `.exe` file...And I use linux...

Istat at this [link](https://www.istat.it/it/archivio/6747) contains interesting links...but today are not working (yesterday from phone worked, so maybe is a temporary issue)

Searching the first site I found a section where they explain various issues the had in fixing foreign countries data taken from Agenzia delle Entrate. At this [link](http://www.elesh.it/storiastati/documentazione.asp#aggiusta) they explain everithing and **there is a [download link](http://www.elesh.it/public/ESTERI.zip) for data in xls format**

**Comment by fabiocaccamo** [comment]
@giobber I finally had some time for checking the data sources you linked:

---

> I've searched for my case on google and i found the history of code for Serbia in this [site](http://www.elesh.it/storiastati/storia_stato.asp?codcat=Z118)

Nice info, but not so useful for automating data updates.

---

> Istat at this [link](https://www.istat.it/it/archivio/6747) contains interesting links...but today are not working (yesterday from phone worked, so maybe is a temporary issue)

Good resource, especially [this file](https://www.istat.it/it/files//2011/01/Elenco-Paesi-esteri-cessati.zip), checking the data there is a problem: there is not the precise date (only the year) when the country has been "removed".

Frankly I would use the Istat data-source, but it's incomplete. :(

---

> Searching the first site I found a section where they explain various issues the had in fixing foreign countries data taken from Agenzia delle Entrate. At this [link](http://www.elesh.it/storiastati/documentazione.asp#aggiusta) they explain everithing and there is a [download link](http://www.elesh.it/public/ESTERI.zip) for data in xls format

Here there are certainly more detailed info, but if you check for "Iugoslavia" there are six rows with different dates (one row for each new country).

**Comment by WaYdotNET** [comment]
missing also Z135 http://www.elesh.it/storiastati/storia_stato.asp?codcat=Z135

**Comment by fabiocaccamo** [comment]
@WaYdotNET thanks for reporting it.

**Comment by fabiocaccamo** [comment]
@giobber @WaYdotNET you can upgrade to `0.8.0` version.

**Comment by WaYdotNET** [comment]
Thx @fabiocaccamo

**Comment by fabiocaccamo** [comment]
[Elenco-Paesi-esteri-cessati.csv](https://github.com/fabiocaccamo/python-codicefiscale/files/11204168/Elenco-Paesi-esteri-cessati.csv)
